/*
 * @copyRight by md sarwar hoshen.
 */
import { apiUrl } from "./appConfig";
//
const apiEndpoints = {
  auth: {
    register: `${apiUrl()}/auth/register`,
    verifySignupOtp: `${apiUrl()}/auth/verifySignupOtp`,
    login: `${apiUrl()}/auth/login`,
    refreshToken: `${apiUrl()}/auth/refreshToken`,
    logout: `${apiUrl()}/auth/logout`,
    changePassword: `${apiUrl()}/auth/changePassword`,
    sendforgotPasswordOtp: `${apiUrl()}/auth/sendforgotPasswordOtp`,
    changeForgotPassword: `${apiUrl()}/auth/changeForgotPassword`,
    requestOtp: `${apiUrl()}/auth/requestOtp`,
  },
  admin: {
    registerDoctor: `${apiUrl()}/admin/registerDoctor`,
    getAllDoctors: `${apiUrl()}/admin/getAllDoctors`,
    updateDoctor: `${apiUrl()}/admin/updateDoctor`,
    deleteDoctor: `${apiUrl()}/admin/deleteDoctor`,
    registerNurse: `${apiUrl()}/admin/registerNurse`,
    updateNurse: `${apiUrl()}/admin/updateNurse`,
    deleteNurse: `${apiUrl()}/admin/deleteNurse`,
    getAllNurses: `${apiUrl()}/admin/getAllNurses`,
    getAllNursesByDeptOrg: `${apiUrl()}/admin/getAllNursesByDeptOrg`,
    registerPharmacy: `${apiUrl()}/admin/registerPharmacy`,
    updatePharmacy: `${apiUrl()}/admin/updatePharmacy`,
    deletePharmacy: `${apiUrl()}/admin/deletePharmacy`,
    getAllPharmacies: `${apiUrl()}/admin/getAllPharmacies`,
    createDepartment: `${apiUrl()}/admin/createDepartment`,
    getAllDepartments: `${apiUrl()}/admin/getAllDepartments`,
    updadteDepartment: `${apiUrl()}/admin/updadteDepartment`,
    createOrganization: `${apiUrl()}/admin/createOrganization`,
    getAllOrganizations: `${apiUrl()}/admin/getAllOrganizations`,
    updadteOrganization: `${apiUrl()}/admin/updadteOrganization`,
    getProfile: `${apiUrl()}/admin/get-profile`,
  },
  doctor: {
    getProfile: `${apiUrl()}/doctor/get-profile`,
    updateProfile: `${apiUrl()}/doctor/update-profile`,
    getHolidays: `${apiUrl()}/doctor/get-holidays`,
    updateHolidays: `${apiUrl()}/doctor/update-holidays`,
    createTimeSlots: `${apiUrl()}/doctor/create-time-slots`,
    updateTimeSlots: `${apiUrl()}/doctor/update-time-slots`,
    getTimeSlots: `${apiUrl()}/doctor/get-time-slots`,
    getTimeSlotsByDate: `${apiUrl()}/doctor/get-time-slots-by-date`,
    getAppointments: `${apiUrl()}/doctor/get-appointments`,
    acceptAppointments: `${apiUrl()}/doctor/accept-appointments`,
    updateAppointments: `${apiUrl()}/doctor/update-appointments`,
    cancelAppointments: `${apiUrl()}/doctor/cancel-appointments`,
    getAppointmentsHistory: `${apiUrl()}/doctor/get-appointments-history`,
    getPrescriptions: `${apiUrl()}/doctor/get-prescriptions`,
    createPrescription: `${apiUrl()}/doctor/create-prescription`,
    createRepeatPrescription: `${apiUrl()}/doctor/create-repeat-prescription`,
    getMedicineSuggestions: `${apiUrl()}/doctor/get-medicine-suggestions`,
    getOrgPharmacy: `${apiUrl()}/doctor/get-org-pharmacy`,
  },
  patient: {
    getProfile: `${apiUrl()}/patient/get-profile`,
    updateProfile: `${apiUrl()}/patient/update-profile`,
    getDept: `${apiUrl()}/patient/get-dept`,
    getDoctors: `${apiUrl()}/patient/get-doctors`,
    getAllDoctors: `${apiUrl()}/patient/get-all-doctors`,
    getAllDoctorsDate: `${apiUrl()}/patient/get-all-doctors-date`,
    getTimeSlots: `${apiUrl()}/patient/get-time-slots`,
    createAppointment: `${apiUrl()}/patient/create-appointment`,
    getAppointments: `${apiUrl()}/patient/get-appointments`,
    getAppointmentsHistory: `${apiUrl()}/patient/get-appointments-history`,
    cancelAppointments: `${apiUrl()}/patient/cancel-appointments`,
    updateAppointments: `${apiUrl()}/patient/update-appointments`,
    getPrescriptions: `${apiUrl()}/patient/get-prescriptions`,
    requestPrescription: `${apiUrl()}/patient/request-prescription`,
  },
  pharmacy: {
    getProfile: `${apiUrl()}/pharmacy/get-profile`,
    updateProfile: `${apiUrl()}/pharmacy/update-profile`,
    getPrescriptions: `${apiUrl()}/pharmacy/get-prescriptions`,
    updatePrescription: `${apiUrl()}/pharmacy/update-prescription`,
    findPrescriptions: `${apiUrl()}/pharmacy/find-prescriptions`,
  },
  stripe: {
    makePayment: `${apiUrl()}/stripe/make-payment`,
    updateTransactionDetails: `${apiUrl()}/stripe/update-transaction-details`,
    makeRefund: `${apiUrl()}/stripe/make-refund`,
  },
  apt: {
    getAppointmentsDetails: `${apiUrl()}/apt/get-appointments-details`,
  },
  nurse: {
    getProfile: `${apiUrl()}/nurse/get-profile`,
    updateProfile: `${apiUrl()}/nurse/update-profile`,
    getDoctors: `${apiUrl()}/nurse/get-doctors`,
    getAllDepartments: `${apiUrl()}/nurse/getAllDepartments`,
    getHolidays: `${apiUrl()}/nurse/get-holidays`,
    updateHolidays: `${apiUrl()}/nurse/update-holidays`,
    createTimeSlots: `${apiUrl()}/nurse/create-time-slots`,
    updateTimeSlots: `${apiUrl()}/nurse/update-time-slots`,
    getTimeSlots: `${apiUrl()}/nurse/get-time-slots`,
    getTimeSlotsByDate: `${apiUrl()}/nurse/get-time-slots-by-date`,

    getAppointments: `${apiUrl()}/nurse/get-appointments`,
    acceptAppointments: `${apiUrl()}/nurse/accept-appointments`,
    updateAppointments: `${apiUrl()}/nurse/update-appointments`,
    cancelAppointments: `${apiUrl()}/nurse/cancel-appointments`,
    getAppointmentsHistory: `${apiUrl()}/nurse/get-appointments-history`,

    updatePatientRecord: `${apiUrl()}/nurse/update-patient-record`,
  },
  upload: {
    url: `${apiUrl()}/uploads`,
  },
};
//
export default apiEndpoints;