/*
 * @copyRight by md sarwar hoshen.
 */
const allergiesLists = [
  "Penicillin",
  "Peanuts",
  "Latex",
  "Sulfonamides",
  "Shellfish",
  "Eggs",
  "Milk",
  "Soy",
  "Wheat",
  "Fish",
  "Tree nuts",
  "Corn",
  "Insect stings",
  "Medications",
];
//
const prescriptionInstructionsOptions = [
  "Before meals",
  "Use as much as desired",
  "Twice a day",
  "With food",
  "Every other day",
  "After meals",
  "Every day",
  "Every hour",
  "Every night at bedtime",
  "Every three hours",
  "Four times a day",
  "Every week",
  "Three times a day",
  "Times",
  "Daily",
  "Morning",
  "Twice daily, 12-hrly",
  "Three times daily, 8-hrly",
  "Four times daily, 6-hrly",
  "Six times daily, 4-hrly",
  "As required",
  "With/after food",
];
//
const validOptions = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  // 'One Time Use'
];
//
const repeatOptions = ["Yes", "No"];
//
const diagnosesLists = [
  "Hypertension",
  "Type 2 Diabetes",
  "Asthma",
  "Coronary Artery Disease",
  "Chronic Obstructive Pulmonary Disease (COPD)",
  "Congestive Heart Failure (CHF)",
  "Osteoarthritis",
  "Rheumatoid Arthritis",
  "Hyperlipidemia",
  "Gastroesophageal Reflux Disease (GERD)",
  "Depression",
  "Anxiety",
  "Thyroid Disorders",
  "Stroke",
  "Chronic Kidney Disease (CKD)",
  "Cancer",
  "Chronic Liver Disease",
  "Peptic Ulcer Disease",
  "Obstructive Sleep Apnea",
  "Human Immunodeficiency Virus (HIV) / Acquired Immunodeficiency Syndrome (AIDS)",
  "Chronic Hepatitis B or C",
  "Epilepsy",
  "Chronic Migraine",
  "Autoimmune Diseases",
  "Inflammatory Bowel Disease",
  "Chronic Fatigue Syndrome",
  "Parkinson's Disease",
  "Multiple Sclerosis",
  "Systemic Lupus Erythematosus (SLE)",
  "Chronic Pancreatitis",
  "Fibromyalgia",
  "Interstitial Cystitis",
  "Endometriosis",
  "Chronic Pain Syndrome",
  "Post-Traumatic Stress Disorder (PTSD)",
  "Bipolar Disorder",
  "Schizophrenia",
  "Obsessive-Compulsive Disorder (OCD)",
  "Attention Deficit Hyperactivity Disorder (ADHD)",
  "Autism Spectrum Disorder (ASD)",
  "Alzheimer's Disease",
  "Dementia",
  "Pulmonary Embolism",
  "Deep Vein Thrombosis",
  "Arrhythmias",
  "Chronic Bronchitis",
  "Fatty Liver Disease",
  "Cirrhosis",
  "Gallstones",
  "Diverticulitis",
  "Crohn's Disease",
  "Ulcerative Colitis",
  "Pneumonia",
  "Tuberculosis",
  "Osteoporosis",
  "Scoliosis",
  "Carpal Tunnel Syndrome",
  "Herniated Disc",
  "Menopause",
  "Erectile Dysfunction",
  "Premenstrual Syndrome (PMS)",
  "Polycystic Ovary Syndrome (PCOS)",
  "Infertility",
  "Miscarriage",
  "Preterm Birth",
  "Low Back Pain",
  "Sciatica",
  "Plantar Fasciitis",
  "Rotator Cuff Tear",
  "Tennis Elbow",
  "ACL Tear",
  "Meniscus Tear",
  "Frozen Shoulder",
  "Concussion",
  "Cerebral Palsy",
  "Muscular Dystrophy",
  "Cystic Fibrosis",
  "Sickle Cell Disease",
  "Hemophilia",
  "Thalassemia",
  "Von Willebrand Disease",
  "Glaucoma",
  "Cataracts",
  "Macular Degeneration",
  "Diabetic Retinopathy",
  "Retinal Detachment",
  "Hearing Loss",
  "Tinnitus",
  "Vertigo",
  "Gastrointestinal Bleeding",
  "Hemorrhoids",
  "Diverticulosis",
  "Pancreatitis",
  "Gastritis",
  "Esophageal Cancer",
  "Colon Cancer",
  "Leukemia",
  "Lymphoma",
  "Melanoma",
  "Prostate Cancer",
  "Breast Cancer",
  "Cervical Cancer",
  "Ovarian Cancer",
  "Uterine Cancer",
  "Testicular Cancer",
  "Lung Cancer",
  "Liver Cancer",
  "Brain Tumor",
  "Multiple Myeloma",
  "Sarcoma",
  "Hypothyroidism",
  "Hyperthyroidism",
  "Thyroid Cancer",
  "Addison's Disease",
  "Cushing's Syndrome",
  "Pheochromocytoma",
  "Hyperparathyroidism",
  "Hypoparathyroidism",
  "Diabetic Ketoacidosis",
  "Hyperosmolar Hyperglycemic State",
  "Hypoglycemia",
  "Diabetic Neuropathy",
  "Diabetic Nephropathy",
  "Diabetic Retinopathy",
  "Diabetic Foot",
  "Metabolic Syndrome",
  "Lupus Nephritis",
  "Nephrotic Syndrome",
  "Polycystic Kidney Disease",
  "Renal Cell Carcinoma",
  "Bladder Cancer",
  "Urinary Tract Infection (UTI)",
  "Kidney Stones",
  "Glomerulonephritis",
  "End-Stage Renal Disease (ESRD)",
  "Acute Renal Failure",
  "Chronic Renal Failure",
  "Anemia",
  "Iron Deficiency Anemia",
  "Vitamin B12 Deficiency Anemia",
  "Folate Deficiency Anemia",
  "Hemolytic Anemia",
  "Sickle Cell Anemia",
  "Thalassemia",
  "Aplastic Anemia",
  "Pernicious Anemia",
  "Idiopathic Thrombocytopenic Purpura (ITP)",
  "Hemophilia",
  "Von Willebrand Disease",
  "Leukemia",
  "Lymphoma",
  "Multiple Myeloma",
  "Myelodysplastic Syndrome",
  "Myeloproliferative Disorders",
  "Thrombotic Thrombocytopenic Purpura (TTP)",
  "Hypertensive Heart Disease",
  "Ischemic Heart Disease",
  "Rheumatic Heart Disease",
  "Congenital Heart Disease",
  "Valvular Heart Disease",
  "Cardiomyopathy",
  "Myocarditis",
  "Pericarditis",
  "Cor Pulmonale",
  "Endocarditis",
  "Peripheral Arterial Disease (PAD)",
  "Atherosclerosis",
  "Varicose Veins",
  "Deep Vein Thrombosis (DVT)",
  "Pulmonary Embolism (PE)",
  "Raynaud's Disease",
  "Buerger's Disease",
  "Aortic Aneurysm",
  "Aortic Dissection",
  "Thoracic Outlet Syndrome",
  "Carotid Artery Disease",
  "Abdominal Aortic Aneurysm",
  "Fibromuscular Dysplasia",
  "Chronic Venous Insufficiency (CVI)",
  "Lymphedema",
  "Aortic Stenosis",
  "Mitral Valve Prolapse",
  "Tricuspid Valve Disease",
  "Pulmonary Valve Disease",
  "Aortic Regurgitation",
  "Mitral Regurgitation",
  "Tricuspid Regurgitation",
  "Pulmonary Regurgitation",
  "Pericardial Effusion",
  "Cardiac Tamponade",
];
//
export {
    allergiesLists,
  prescriptionInstructionsOptions,
  validOptions,
  repeatOptions,
  diagnosesLists
};
